### ISSUE TITLE
Sync successful but did not pull emails to google group

### ISSUE THREAD

**Issue by snapcase303** [veda-consulting/uk.co.vedaconsulting.googlegroup#11]
I setup the extension and followed the instructions to get the api setup and it is now connected to google. When i run the sync it says the sync was successful but no information or email addresses are pulled over to the google group that i am trying to sync. Any thoughts on why this would be happening?

**Comment by Ishaqzamueani** [comment]
3747 use client key and client secret key from configuration setting #12

**Comment by veda-consulting** [comment]
Merged PR thanks @Ishaqzamueani
